# Generated by Django 3.1.3 on 2021-09-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='질문 제목')),
                ('content', models.TextField(verbose_name='질문 내용')),
                ('create_date', models.DateField(verbose_name='등록일자')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답변 내용')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='등록일자')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question', verbose_name='답변')),
            ],
        ),
    ]
